# fly.toml app configuration file generated for jinalyang-fly on 2023-06-04T01:12:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jinalyang-fly"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = ""
  internal_port = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
