spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: //
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  profiles:
    include: oauth
server:
  address: 0.0.0.0
  port: 8080

